package com.ceslab.team7_ble_meet.ble

object Characteristic {
    var sex = mutableMapOf<Int,String>().apply{
        put(0,"Male")
        put(1,"Female")
    }
    var sexualOrientation = mutableMapOf<Int,String>().apply{
        put(0,"Male")
        put(1,"Female")
        put(2,"Both")
    }

    var Tag = mutableMapOf<String,Int>().apply {
        put("Intimate Chat",0)
        put("Walking",1)
        put("Karaoke",2)
        put("17DTV",3)
        put("Trying New Things",4)
        put("Swimming",5)
        put("Esports",6)
        put("Chatting When I'm Bored",7)
        put("Photography",8)
        put("Instagram",9)
        put("Street Food",10)
        put("Dancing",11)
        put("Music",12)
        put("Outdoors",13)
        put("Sapiosexual",14)
        put("Art",15)
        put("Korean Dramas",16)
        put("Working out",17)
        put("Environentalism",18)
        put("BTS",19)
        put("Pho",20)
        put("PotterHead",21)
        put("Horror Movies",22)
        put("Comedy",23)
        put("Athlete",24)
        put("Shopping",25)
        put("Festivals",26)
        put("Geek",27)
        put("Golf",28)
        put("Board Games",29)
        put("Hot Pot",30)
        put("Picnicking",31)
        put("Running",32)
        put("Go for a drive",33)
        put("Hip Hop",34)
        put("LGBT+",35)
        put("Hiking",36)
        put("Disney",37)
        put("Vlogging",38)
        put("Vegan",39)
        put("Travel",40)
        put("Anime",41)
        put("Student",42)
        put("Cocking",43)
        put("Cat lover",44)
        put("Craft Beer",45)
        put("Foodie",46)
        put("Coffee",47)
        put("Writer",48)
        put("Gamer",49)
        put("Wine",50)
        put("Bun cha",51)
        put("Dog lover",52)
        put("Gemini",53)
        put("Tea",54)
        put("Taurus",55)
        put("Aquarius",56)
        put("Plant-based",57)
        put("Nightlife",58)
        put("Motorcycles",59)
        put("Politic",60)
        put("Soccer",61)
        put("Basketball",62)
        put("Fashion",63)
        put("Gardening",64)
        put("StreetFood",65)
    }
}

//var sex = mutableMapOf<Int,String>().apply{
//    put(0,"")
//    put(1,"Male")
//    put(2,"Female")
//    put(3,"Bisexual")
//    put(4,"Female Transgender")
//    put(5,"Male Transgender")
//    put(6,"Questioning")
//    put(7,"NonBinary")
//}

//var sexualOrientation = mutableMapOf<Int,String>().apply{
//    put(0,"")
//    put(1,"Straight")
//    put(2,"Gay")
//    put(3,"Lesibian")
//    put(4,"Bisexual")
//    put(5,"Asexual")
//    put(6,"Pansexuality")
//    put(7,"Demisexual")
//}

//var zodiac = mutableMapOf<Int,String>().apply{
//    put(0,"")
//    put(1,"Bạch Dương")
//    put(2,"Kim Ngưu")
//    put(3,"Song Tử")
//    put(4,"Cự Giải")
//    put(5,"Sư Tử")
//    put(6,"Xử Nữ")
//    put(7,"Thiên Bình")
//    put(8,"Bọ Cạp")
//    put(9,"Nhân Mã")
//    put(10,"Ma Kết")
//    put(11,"Bảo Bình")
//    put(10,"Song Ngư")
//}
//var hightlight = mutableMapOf<Int,String>().apply{
//    put(0,"")
//    put(1,"sushi")
//    put(2,"music")
//    put(3,"art")
//    put(4,"dancing")
//    put(5,"photography")
//    put(6,"street food")
//    put(7,"athlete")
//    put(8,"baking")
//    put(9,"shopping")
//    put(10,"outdoors")
//    put(11,"walking")
//    put(12,"traveling")
//    put(13,"v-pop")
//    put(14,"cat lover")
//    put(15,"soccer")
//    put(16,"coffee")
//    put(17,"chatting")
//    put(18,"sports")
//    put(19,"politics")
//    put(20,"gaming")
//    put(21,"bun cha")
//    put(22,"nightlife")
//    put(23,"dog lover")
//    put(24,"tea")
//    put(25,"yoga")
//    put(26,"singing")
//    put(27,"fishing")
//    put(28,"car")
//    put(29,"gun")
//    put(30,"anime")
//}
//var character = mutableMapOf<Int,String>().apply {
//    put(1,"active")
//    put(2,"advanced")
//    put(3,"adventurous")
//    put(4,"aggressive")
//    put(5,"ambitious")
//    put(6,"amicable")
//    put(7,"annoying")
//    put(8,"arrogant")
//    put(9,"artistic")
//    put(10,"boring")
//    put(11,"bossy")
//    put(12,"calm")
//    put(13,"caring")
//    put(14,"cautious")
//    put(15,"confident")
//    put(16,"competitive")
//    put(17,"cool")
//    put(18,"cruel")
//    put(19,"dangerous")
//    put(20,"dirty")
//    put(21,"educated")
//    put(22,"friendly")
//    put(23,"happy")
//    put(24,"ignorant")
//    put(25,"lazy")
//    put(26,"loyal")
//    put(27,"nice")
//    put(28,"patient")
//    put(29,"pushy")
//    put(30,"romantic")
//}
//var job = mutableMapOf<Int,String>().apply {
//    put(1,"actor")
//    put(2,"apprentice")
//    put(3,"architect")
//    put(4,"artist")
//    put(5,"lawyer")
//    put(6,"baker")
//    put(7,"cashier")
//    put(8,"researcher")
//    put(9,"hairstylist")
//    put(10,"comedian")
//    put(11,"dancer")
//    put(12,"dentist")
//    put(13,"doctor")
//    put(14,"writer")
//    put(15,"teacher")
//    put(16,"student")
//    put(17,"farmer")
//    put(18,"florist")
//    put(19,"manager")
//    put(20,"judge")
//    put(21,"nurse")
//    put(22,"pilot")
//    put(23,"general")
//    put(24,"driver")
//    put(25,"singer")
//    put(26,"engineer")
//    put(27,"programmer")
//    put(28,"police officer")
//    put(29,"waiter")
//    put(30,"president")
//}
//var outlook = mutableMapOf<Int,String>().apply {
//    put(1,"agile")
//    put(2,"ample")
//    put(3,"barrel-chested")
//    put(4,"big")
//    put(5,"bony")
//    put(6,"busty")
//    put(7,"chunky")
//    put(8,"curvy")
//    put(9,"developed")
//    put(10,"elfin")
//    put(11,"fat")
//    put(12,"fit")
//    put(13,"flat-chested")
//    put(14,"giant")
//    put(15,"full-grown")
//    put(16,"heavy")
//    put(17,"leggy")
//    put(18,"meaty")
//    put(19,"muscular")
//    put(20,"overweight")
//    put(21,"pudgy")
//    put(22,"rounded")
//    put(23,"skeletal")
//    put(24,"small")
//    put(25,"stocky")
//    put(26,"sweating")
//    put(27,"teeny")
//    put(28,"thicc")
//    put(29,"thin")
//    put(30,"undersized")
//}