package com.ceslab.team7_ble_meet.ble

class Character {
    fun testmap() {
        var passion = mutableMapOf<Int,String>()
        passion.put(1,"sushi")
        passion.put(2,"music")
        passion.put(3,"art")
        passion.put(4,"dancing")
        passion.put(5,"photography")
        passion.put(6,"street food")
        passion.put(7,"athlete")
        passion.put(8,"baking")
        passion.put(9,"shopping")
        passion.put(10,"outdoors")
        passion.put(11,"walking")
        passion.put(12,"traveling")
        passion.put(13,"v-pop")
        passion.put(14,"cat lover")
        passion.put(15,"soccer")
        passion.put(16,"coffee")
        passion.put(17,"chatting")
        passion.put(18,"sports")
        passion.put(19,"politics")
        passion.put(20,"gaming")
        passion.put(21,"bun cha")
        passion.put(22,"nightlife")
        passion.put(23,"dog lover")
        passion.put(24,"tea")
        passion.put(25,"yoga")
        passion.put(26,"singing")
        passion.put(27,"fishing")
        passion.put(28,"car")
        passion.put(29,"gun")
        passion.put(30,"anime")

        var personality = mutableMapOf<Int,String>()
        personality.put(1,"active")
        personality.put(2,"advanced")
        personality.put(3,"adventurous")
        personality.put(4,"aggressive")
        personality.put(5,"ambitious")
        personality.put(6,"amicable")
        personality.put(7,"annoying")
        personality.put(8,"arrogant")
        personality.put(9,"artistic")
        personality.put(10,"boring")
        personality.put(11,"bossy")
        personality.put(12,"calm")
        personality.put(13,"caring")
        personality.put(14,"cautious")
        personality.put(15,"confident")
        personality.put(16,"competitive")
        personality.put(17,"cool")
        personality.put(18,"cruel")
        personality.put(19,"dangerous")
        personality.put(20,"dirty")
        personality.put(21,"educated")
        personality.put(22,"friendly")
        personality.put(23,"happy")
        personality.put(24,"ignorant")
        personality.put(25,"lazy")
        personality.put(26,"loyal")
        personality.put(27,"nice")
        personality.put(28,"patient")
        personality.put(29,"pushy")
        personality.put(30,"romantic")

        var job = mutableMapOf<Int,String>()
        job.put(1,"actor")
        job.put(2,"apprentice")
        job.put(3,"architect")
        job.put(4,"artist")
        job.put(5,"lawyer")
        job.put(6,"baker")
        job.put(7,"cashier")
        job.put(8,"researcher")
        job.put(9,"hairstylist")
        job.put(10,"comedian")
        job.put(11,"dancer")
        job.put(12,"dentist")
        job.put(13,"doctor")
        job.put(14,"writer")
        job.put(15,"teacher")
        job.put(16,"student")
        job.put(17,"farmer")
        job.put(18,"florist")
        job.put(19,"manager")
        job.put(20,"judge")
        job.put(21,"nurse")
        job.put(22,"pilot")
        job.put(23,"general")
        job.put(24,"driver")
        job.put(25,"singer")
        job.put(26,"engineer")
        job.put(27,"programmer")
        job.put(28,"police officer")
        job.put(29,"waiter")
        job.put(30,"president")

        var body_trait = mutableMapOf<Int,String>()
        body_trait.put(1,"agile")
        body_trait.put(2,"ample")
        body_trait.put(3,"barrel-chested")
        body_trait.put(4,"big")
        body_trait.put(5,"bony")
        body_trait.put(6,"busty")
        body_trait.put(7,"chunky")
        body_trait.put(8,"curvy")
        body_trait.put(9,"developed")
        body_trait.put(10,"elfin")
        body_trait.put(11,"fat")
        body_trait.put(12,"fit")
        body_trait.put(13,"flat-chested")
        body_trait.put(14,"giant")
        body_trait.put(15,"full-grown")
        body_trait.put(16,"heavy")
        body_trait.put(17,"leggy")
        body_trait.put(18,"meaty")
        body_trait.put(19,"muscular")
        body_trait.put(20,"overweight")
        body_trait.put(21,"pudgy")
        body_trait.put(22,"rounded")
        body_trait.put(23,"skeletal")
        body_trait.put(24,"small")
        body_trait.put(25,"stocky")
        body_trait.put(26,"sweating")
        body_trait.put(27,"teeny")
        body_trait.put(28,"thicc")
        body_trait.put(29,"thin")
        body_trait.put(30,"undersized")
    }
}