package com.ceslab.team7_ble_meet.ble

object Characteristic {
    var sex = mutableMapOf<Int,String>().apply{
        put(0,"Male")
        put(1,"Female")
    }
    var sexualOrientation = mutableMapOf<Int,String>().apply{
        put(0,"Male")
        put(1,"Female")
        put(2,"Both")
    }

    var Tag = mutableMapOf<Int,String>().apply {
        put(0, "Intimate Chat")
        put(1,"Walking")
        put(2,"Karaoke")
        put(3,"17DTV")
        put(4,"Sushi")
        put(5,"Trying New Things")
        put(6,"Swimming")
        put(7,"Esports")
        put(8,"Chatting When I'm Bored")
        put(9,"Photography")
        put(10,"Instagram")
        put(11,"Street Food")
        put(12,"Dancing")
        put(13,"Music")
        put(14,"Outdoors")
        put(15,"Sapiosexual")
        put(16,"Art")
        put(17,"Korean Dramas")
        put(18,"Working out")
        put(19,"Environentalism")
        put(20,"BTS")
        put(21,"Pho")
        put(22,"PotterHead")
        put(23,"Horror Movies")
        put(24,"Comedy")
        put(25,"Athlete")
        put(26,"Shopping")
        put(27,"Festivals")
        put(28,"Geek")
        put(29,"Golf")
        put(30,"Board Games")
        put(31,"Hot Pot")
        put(32,"Picnicking")
        put(33,"Running")
        put(34,"Go for a drive")
        put(35,"Hip Hop")
        put(36,"LGBT+")
        put(37,"Hiking")
        put(38,"Disney")
        put(39,"Vlogging")
        put(40,"Vegan")
        put(41,"Travel")
        put(42,"Anime")
        put(43,"Student")
        put(44,"Cocking")
        put(45,"Cat lover")
        put(46,"Craft Beer")
        put(47,"Foodie")
        put(48,"Coffee")
        put(49,"Writer")
        put(50,"Gamer")
        put(51,"Wine")
        put(52,"Bun cha")
        put(53,"Dog lover")
        put(54,"Gemini")
        put(55,"Tea")
        put(56,"Taurus")
        put(57,"Aquarius")
        put(58,"Plant-based")
        put(59,"Nightlife")
        put(60,"Motorcycles")
        put(61,"Politic")
        put(62,"Soccer")
        put(63,"Basketball")
        put(64,"Fashion")
        put(65,"Gardening")
        put(66,"StreetFood")
    }
}

//var sex = mutableMapOf<Int,String>().apply{
//    put(0,"")
//    put(1,"Male")
//    put(2,"Female")
//    put(3,"Bisexual")
//    put(4,"Female Transgender")
//    put(5,"Male Transgender")
//    put(6,"Questioning")
//    put(7,"NonBinary")
//}

//var sexualOrientation = mutableMapOf<Int,String>().apply{
//    put(0,"")
//    put(1,"Straight")
//    put(2,"Gay")
//    put(3,"Lesibian")
//    put(4,"Bisexual")
//    put(5,"Asexual")
//    put(6,"Pansexuality")
//    put(7,"Demisexual")
//}

//var zodiac = mutableMapOf<Int,String>().apply{
//    put(0,"")
//    put(1,"Bạch Dương")
//    put(2,"Kim Ngưu")
//    put(3,"Song Tử")
//    put(4,"Cự Giải")
//    put(5,"Sư Tử")
//    put(6,"Xử Nữ")
//    put(7,"Thiên Bình")
//    put(8,"Bọ Cạp")
//    put(9,"Nhân Mã")
//    put(10,"Ma Kết")
//    put(11,"Bảo Bình")
//    put(10,"Song Ngư")
//}
//var hightlight = mutableMapOf<Int,String>().apply{
//    put(0,"")
//    put(1,"sushi")
//    put(2,"music")
//    put(3,"art")
//    put(4,"dancing")
//    put(5,"photography")
//    put(6,"street food")
//    put(7,"athlete")
//    put(8,"baking")
//    put(9,"shopping")
//    put(10,"outdoors")
//    put(11,"walking")
//    put(12,"traveling")
//    put(13,"v-pop")
//    put(14,"cat lover")
//    put(15,"soccer")
//    put(16,"coffee")
//    put(17,"chatting")
//    put(18,"sports")
//    put(19,"politics")
//    put(20,"gaming")
//    put(21,"bun cha")
//    put(22,"nightlife")
//    put(23,"dog lover")
//    put(24,"tea")
//    put(25,"yoga")
//    put(26,"singing")
//    put(27,"fishing")
//    put(28,"car")
//    put(29,"gun")
//    put(30,"anime")
//}
//var character = mutableMapOf<Int,String>().apply {
//    put(1,"active")
//    put(2,"advanced")
//    put(3,"adventurous")
//    put(4,"aggressive")
//    put(5,"ambitious")
//    put(6,"amicable")
//    put(7,"annoying")
//    put(8,"arrogant")
//    put(9,"artistic")
//    put(10,"boring")
//    put(11,"bossy")
//    put(12,"calm")
//    put(13,"caring")
//    put(14,"cautious")
//    put(15,"confident")
//    put(16,"competitive")
//    put(17,"cool")
//    put(18,"cruel")
//    put(19,"dangerous")
//    put(20,"dirty")
//    put(21,"educated")
//    put(22,"friendly")
//    put(23,"happy")
//    put(24,"ignorant")
//    put(25,"lazy")
//    put(26,"loyal")
//    put(27,"nice")
//    put(28,"patient")
//    put(29,"pushy")
//    put(30,"romantic")
//}
//var job = mutableMapOf<Int,String>().apply {
//    put(1,"actor")
//    put(2,"apprentice")
//    put(3,"architect")
//    put(4,"artist")
//    put(5,"lawyer")
//    put(6,"baker")
//    put(7,"cashier")
//    put(8,"researcher")
//    put(9,"hairstylist")
//    put(10,"comedian")
//    put(11,"dancer")
//    put(12,"dentist")
//    put(13,"doctor")
//    put(14,"writer")
//    put(15,"teacher")
//    put(16,"student")
//    put(17,"farmer")
//    put(18,"florist")
//    put(19,"manager")
//    put(20,"judge")
//    put(21,"nurse")
//    put(22,"pilot")
//    put(23,"general")
//    put(24,"driver")
//    put(25,"singer")
//    put(26,"engineer")
//    put(27,"programmer")
//    put(28,"police officer")
//    put(29,"waiter")
//    put(30,"president")
//}
//var outlook = mutableMapOf<Int,String>().apply {
//    put(1,"agile")
//    put(2,"ample")
//    put(3,"barrel-chested")
//    put(4,"big")
//    put(5,"bony")
//    put(6,"busty")
//    put(7,"chunky")
//    put(8,"curvy")
//    put(9,"developed")
//    put(10,"elfin")
//    put(11,"fat")
//    put(12,"fit")
//    put(13,"flat-chested")
//    put(14,"giant")
//    put(15,"full-grown")
//    put(16,"heavy")
//    put(17,"leggy")
//    put(18,"meaty")
//    put(19,"muscular")
//    put(20,"overweight")
//    put(21,"pudgy")
//    put(22,"rounded")
//    put(23,"skeletal")
//    put(24,"small")
//    put(25,"stocky")
//    put(26,"sweating")
//    put(27,"teeny")
//    put(28,"thicc")
//    put(29,"thin")
//    put(30,"undersized")
//}